//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoP_Viewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoP_Viewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rome;16;404040;163000
        ///Milan;12;40403F;124000
        ///Naples;42;403F3F;419000
        ///Turin;9;3F3F3F;90000
        ///Palermo;13;3F3F3E;130000
        ///Genoa;9;3F3E3E;91000
        ///Bologna;7;3E3E3E;68190
        ///Florence;8;3E3E3D;81000
        ///Venice;14;3E3D3D;138000
        ///Bari;2;3D3D3D;20000
        ///Catania;5;3D3D3C;45000
        ///Verona;5;3D3C3C;50000
        ///Messina;5;3C3C3C;54000
        ///Padua;3;3C3C3B;32000
        ///Trieste;2;3C3B3B;20000
        ///Brescia;3;3B3B3B;28000
        ///Parma;3;3B3B3A;34000
        ///Taranto;1;3B3A3A;13000
        ///Modena;3;3A3A3A;26000
        ///Reggio Calabria;3;3A3A39;27000
        ///Reggio Emilia;2;3A3939;23000
        ///Per [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CityData {
            get {
                return ResourceManager.GetString("CityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France;A7AAD7
        ///Spain;C19B4A
        ///Portugal;9BCC8B
        ///Papal States;EEBCD7
        ///Andorra;9C6875
        ///Kingdom of Sardinia;BEDAAA
        ///Republic of Genoa;E3857D
        ///Batavian Republic;B194B2
        ///Swiss Confederation;B9978E
        ///Austria;F8B972
        ///Venice;F18BA3
        ///Parma;9CB5DD
        ///Modena and Reggio;99CDA6
        ///Lucca;DFDA54
        ///Tuscany;F4B298
        ///Piombino;D7E78E
        ///Naples;9E727F
        ///San Marino;DFA951
        ///Corsica;889A8C
        ///Bavaria;759355
        ///Prussia;A1C1D6
        ///Electorate of Saxony;E3998C
        ///Principality of Schwarzburg;8D7995
        ///Hanover;FBF297
        ///Denmark-Norway;FBD2A4
        ///Sweden;A2D9F7
        ///Ru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClaimData {
            get {
                return ResourceManager.GetString("ClaimData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DevastationMap {
            get {
                object obj = ResourceManager.GetObject("DevastationMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OccupationMap {
            get {
                object obj = ResourceManager.GetObject("OccupationMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PoliticalMap {
            get {
                object obj = ResourceManager.GetObject("PoliticalMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lombardy;F8B972;1;0.75.
        /// </summary>
        internal static string RegionData {
            get {
                return ResourceManager.GetString("RegionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RegionMap {
            get {
                object obj = ResourceManager.GetObject("RegionMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grassland;359950;100
        ///River;354ca0;100
        ///Dryland;B29950;60
        ///Hill;99592f;30
        ///Forest;184424;20
        ///Steppe;94AF66;10
        ///Mountain;60361e;1
        ///Tundra;86B7B2;0
        ///Tundra Hills;5B6482;0
        ///Desert;F7D36F;0
        ///Desert Hills;B76D45;0.
        /// </summary>
        internal static string TerrainData {
            get {
                return ResourceManager.GetString("TerrainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TerrainMap {
            get {
                object obj = ResourceManager.GetObject("TerrainMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
